// Code generated by drel. DO NOT EDIT.

package db

import (
	"context"

	"github.com/alternayte/drel"
	orders "github.com/alternayte/drel/examples/uuid-keys/orders"
)

type DB struct {
	*drel.Engine
	Orders *orders.OrderRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine: engine,
		Orders: &orders.OrderRepository{Repository: drel.NewRepository(engine, orders.OrderMeta)},
	}, nil
}

// TxRepos holds the tracked repositories of one transaction. Load through
// the fields, stage with Add and Remove, then let WithTx commit.
type TxRepos struct {
	Orders *orders.TxOrderRepository
}

// Tx returns the tracked repositories bound to the transaction in ctx.
// It panics if no transaction is present, so wrap the call in WithTx.
func (db *DB) Tx(ctx context.Context) TxRepos {
	tx := drel.MustFromContext(ctx)
	return TxRepos{
		Orders: &orders.TxOrderRepository{TxRepository: drel.NewTxRepository(tx, orders.OrderMeta)},
	}
}

// WithTx runs fn inside a transaction and puts that transaction in the
// context it passes to fn. Reach the tracked repositories with db.Tx(ctx).
// A nested call opens a savepoint on the same transaction.
func (db *DB) WithTx(ctx context.Context, fn func(ctx context.Context) error, opts ...drel.TxOption) error {
	return db.Engine.WithTx(ctx, fn, opts...)
}
