// Code generated by drel. DO NOT EDIT.

package testmodels

import (
	"context"

	"github.com/alternayte/drel"
)

var AuditOrderLines = struct {
	OrderID   drel.OrderedColumn[int]
	LineNo    drel.ComparableColumn[LineNo]
	Qty       drel.OrderedColumn[int]
	CreatedBy drel.StringColumn
	UpdatedBy drel.StringColumn
	CreatedAt drel.TimeColumn
	UpdatedAt drel.TimeColumn
}{
	OrderID:   drel.NewOrderedCol[int]("order_id"),
	LineNo:    drel.NewComparableCol[LineNo]("line_no"),
	Qty:       drel.NewOrderedCol[int]("qty"),
	CreatedBy: drel.NewStringCol("created_by"),
	UpdatedBy: drel.NewStringCol("updated_by"),
	CreatedAt: drel.NewTimeCol("created_at"),
	UpdatedAt: drel.NewTimeCol("updated_at"),
}

func scanAuditorderline(row drel.Row) (*AuditOrderLine, error) {
	p := &AuditOrderLine{}
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	var k OrderLineKey
	createdByPtr, updatedByPtr := p.AuditPtrs()
	err := row.Scan(&k.OrderID, &k.LineNo, &p.Qty, createdByPtr, updatedByPtr, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	p.SetID(k)
	return p, nil
}

type auditorderlineSnapshot struct {
	Qty int
}

func snapshotAuditorderline(p *AuditOrderLine) any {
	return auditorderlineSnapshot{Qty: p.Qty}
}

func diffAuditorderline(p *AuditOrderLine, snap any) []drel.FieldChange {
	s := snap.(auditorderlineSnapshot)
	var changes []drel.FieldChange
	if p.Qty != s.Qty {
		changes = append(changes, drel.FieldChange{Column: "qty", Value: p.Qty})
	}
	return changes
}

func auditorderlinePKValue(p *AuditOrderLine) any {
	return p.ID()
}

// auditorderlineKeyValues splits a OrderLineKey into one value per key column, in key order.
func auditorderlineKeyValues(key any) []any {
	k := key.(OrderLineKey)
	return []any{k.OrderID, k.LineNo}
}

func auditorderlineColumnValue(p *AuditOrderLine, idx int) any {
	switch idx {
	case 0:
		return p.ID().OrderID
	case 1:
		return p.ID().LineNo
	case 2:
		return p.Qty
	case 3:
		return p.CreatedBy()
	case 4:
		return p.UpdatedBy()
	case 5:
		return p.CreatedAt()
	case 6:
		return p.UpdatedAt()
	}
	return nil
}

func auditorderlineInsertColumns(p *AuditOrderLine) ([]string, []any) {
	return []string{"qty", "created_by", "updated_by"}, []any{p.Qty, p.CreatedBy(), p.UpdatedBy()}
}

func auditorderlineScanReturning(p *AuditOrderLine, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	var k OrderLineKey
	if err := row.Scan(&k.OrderID, &k.LineNo, createdAtPtr, updatedAtPtr); err != nil {
		return err
	}
	p.SetID(k)
	return nil
}

// auditorderlineNormalizeKey converts per-column driver values into a canonical OrderLineKey,
// so a key read back from the driver compares equal to PKValue.
func auditorderlineNormalizeKey(v any) any {
	vals, ok := v.([]any)
	if !ok {
		return v
	}
	if len(vals) != 2 {
		return v
	}
	var k OrderLineKey
	f0, ok := drel.NormalizeIntKey(vals[0]).(int)
	if !ok {
		return v
	}
	k.OrderID = f0
	f1, ok := drel.NormalizeIntKey(vals[1]).(int)
	if !ok {
		return v
	}
	k.LineNo = LineNo(f1)
	return k
}

func auditorderlineKeyIsZero(p *AuditOrderLine) bool {
	var zero OrderLineKey
	return p.ID() == zero
}

func auditorderlineScanGenerated(p *AuditOrderLine, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(createdAtPtr, updatedAtPtr)
}

var AuditOrderLineMeta = drel.ModelMeta[AuditOrderLine]{
	Table:         "audit_order_lines",
	Columns:       []string{"order_id", "line_no", "qty", "created_by", "updated_by", "created_at", "updated_at"},
	PKColumns:     []string{"order_id", "line_no"},
	Scan:          scanAuditorderline,
	Snapshot:      snapshotAuditorderline,
	Diff:          diffAuditorderline,
	PKValue:       auditorderlinePKValue,
	KeyValues:     auditorderlineKeyValues,
	InsertColumns: auditorderlineInsertColumns,
	ScanReturning: auditorderlineScanReturning,
	ColumnValue:   auditorderlineColumnValue,
	NormalizeKey:  auditorderlineNormalizeKey,
	KeyStrategy:   drel.KeyAppAssigned,
	SetKey:        func(p *AuditOrderLine, key any) { p.SetID(key.(OrderLineKey)) },
	KeyIsZero:     auditorderlineKeyIsZero,
	ScanGenerated: auditorderlineScanGenerated,
	HasAudit:      true,
	AuditSetCreate: func(p *AuditOrderLine, actor string) {
		createdByPtr, updatedByPtr := p.AuditPtrs()
		*createdByPtr = actor
		*updatedByPtr = actor
	},
	AuditSetUpdate: func(p *AuditOrderLine, actor string) {
		_, updatedByPtr := p.AuditPtrs()
		*updatedByPtr = actor
	},
}

type AuditOrderLineRepository struct {
	*drel.Repository[AuditOrderLine]
}

func (r *AuditOrderLineRepository) FindByID(ctx context.Context, id OrderLineKey) (*AuditOrderLine, error) {
	return r.Find(ctx, id)
}

type TxAuditOrderLineRepository struct {
	*drel.TxRepository[AuditOrderLine]
}

func (r *TxAuditOrderLineRepository) FindByID(ctx context.Context, id OrderLineKey) (*AuditOrderLine, error) {
	return r.Find(ctx, id)
}
