// Code generated by drel. DO NOT EDIT.

package testmodels

import (
	"context"

	"github.com/alternayte/drel"
)

var OrderLines = struct {
	OrderID   drel.OrderedColumn[int]
	LineNo    drel.ComparableColumn[LineNo]
	Qty       drel.OrderedColumn[int]
	CreatedAt drel.TimeColumn
	UpdatedAt drel.TimeColumn
}{
	OrderID:   drel.NewOrderedCol[int]("order_id"),
	LineNo:    drel.NewComparableCol[LineNo]("line_no"),
	Qty:       drel.NewOrderedCol[int]("qty"),
	CreatedAt: drel.NewTimeCol("created_at"),
	UpdatedAt: drel.NewTimeCol("updated_at"),
}

func scanOrderline(row drel.Row) (*OrderLine, error) {
	p := &OrderLine{}
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	var k OrderLineKey
	err := row.Scan(&k.OrderID, &k.LineNo, &p.Qty, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	p.SetID(k)
	return p, nil
}

type orderlineSnapshot struct {
	Qty int
}

func snapshotOrderline(p *OrderLine) any {
	return orderlineSnapshot{Qty: p.Qty}
}

func diffOrderline(p *OrderLine, snap any) []drel.FieldChange {
	s := snap.(orderlineSnapshot)
	var changes []drel.FieldChange
	if p.Qty != s.Qty {
		changes = append(changes, drel.FieldChange{Column: "qty", Value: p.Qty})
	}
	return changes
}

func orderlinePKValue(p *OrderLine) any {
	return p.ID()
}

// orderlineKeyValues splits a OrderLineKey into one value per key column, in key order.
func orderlineKeyValues(key any) []any {
	k := key.(OrderLineKey)
	return []any{k.OrderID, k.LineNo}
}

func orderlineColumnValue(p *OrderLine, idx int) any {
	switch idx {
	case 0:
		return p.ID().OrderID
	case 1:
		return p.ID().LineNo
	case 2:
		return p.Qty
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func orderlineInsertColumns(p *OrderLine) ([]string, []any) {
	return []string{"qty"}, []any{p.Qty}
}

func orderlineScanReturning(p *OrderLine, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	var k OrderLineKey
	if err := row.Scan(&k.OrderID, &k.LineNo, createdAtPtr, updatedAtPtr); err != nil {
		return err
	}
	p.SetID(k)
	return nil
}

// orderlineNormalizeKey converts per-column driver values into a canonical OrderLineKey,
// so a key read back from the driver compares equal to PKValue.
func orderlineNormalizeKey(v any) any {
	vals, ok := v.([]any)
	if !ok {
		return v
	}
	if len(vals) != 2 {
		return v
	}
	var k OrderLineKey
	f0, ok := drel.NormalizeIntKey(vals[0]).(int)
	if !ok {
		return v
	}
	k.OrderID = f0
	f1, ok := drel.NormalizeIntKey(vals[1]).(int)
	if !ok {
		return v
	}
	k.LineNo = LineNo(f1)
	return k
}

func orderlineKeyIsZero(p *OrderLine) bool {
	var zero OrderLineKey
	return p.ID() == zero
}

func orderlineScanGenerated(p *OrderLine, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(createdAtPtr, updatedAtPtr)
}

var OrderLineMeta = drel.ModelMeta[OrderLine]{
	Table:         "order_lines",
	Columns:       []string{"order_id", "line_no", "qty", "created_at", "updated_at"},
	PKColumns:     []string{"order_id", "line_no"},
	Scan:          scanOrderline,
	Snapshot:      snapshotOrderline,
	Diff:          diffOrderline,
	PKValue:       orderlinePKValue,
	KeyValues:     orderlineKeyValues,
	InsertColumns: orderlineInsertColumns,
	ScanReturning: orderlineScanReturning,
	ColumnValue:   orderlineColumnValue,
	NormalizeKey:  orderlineNormalizeKey,
	KeyStrategy:   drel.KeyAppAssigned,
	SetKey:        func(p *OrderLine, key any) { p.SetID(key.(OrderLineKey)) },
	KeyIsZero:     orderlineKeyIsZero,
	ScanGenerated: orderlineScanGenerated,
}

type OrderLineRepository struct {
	*drel.Repository[OrderLine]
}

func (r *OrderLineRepository) FindByID(ctx context.Context, id OrderLineKey) (*OrderLine, error) {
	return r.Find(ctx, id)
}

type TxOrderLineRepository struct {
	*drel.TxRepository[OrderLine]
}

func (r *TxOrderLineRepository) FindByID(ctx context.Context, id OrderLineKey) (*OrderLine, error) {
	return r.Find(ctx, id)
}
