// Code generated by drel. DO NOT EDIT.

package testmodels

import (
	"context"
	"time"

	"github.com/alternayte/drel"
)

var SoftOrderLines = struct {
	OrderID   drel.OrderedColumn[int]
	LineNo    drel.ComparableColumn[LineNo]
	Qty       drel.OrderedColumn[int]
	DeletedAt drel.ComparableColumn[*time.Time]
	CreatedAt drel.TimeColumn
	UpdatedAt drel.TimeColumn
}{
	OrderID:   drel.NewOrderedCol[int]("order_id"),
	LineNo:    drel.NewComparableCol[LineNo]("line_no"),
	Qty:       drel.NewOrderedCol[int]("qty"),
	DeletedAt: drel.NewComparableCol[*time.Time]("deleted_at"),
	CreatedAt: drel.NewTimeCol("created_at"),
	UpdatedAt: drel.NewTimeCol("updated_at"),
}

func scanSoftorderline(row drel.Row) (*SoftOrderLine, error) {
	p := &SoftOrderLine{}
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	var k OrderLineKey
	err := row.Scan(&k.OrderID, &k.LineNo, &p.Qty, p.DeletedAtPtr(), createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	p.SetID(k)
	return p, nil
}

type softorderlineSnapshot struct {
	Qty int
}

func snapshotSoftorderline(p *SoftOrderLine) any {
	return softorderlineSnapshot{Qty: p.Qty}
}

func diffSoftorderline(p *SoftOrderLine, snap any) []drel.FieldChange {
	s := snap.(softorderlineSnapshot)
	var changes []drel.FieldChange
	if p.Qty != s.Qty {
		changes = append(changes, drel.FieldChange{Column: "qty", Value: p.Qty})
	}
	return changes
}

func softorderlinePKValue(p *SoftOrderLine) any {
	return p.ID()
}

// softorderlineKeyValues splits a OrderLineKey into one value per key column, in key order.
func softorderlineKeyValues(key any) []any {
	k := key.(OrderLineKey)
	return []any{k.OrderID, k.LineNo}
}

func softorderlineColumnValue(p *SoftOrderLine, idx int) any {
	switch idx {
	case 0:
		return p.ID().OrderID
	case 1:
		return p.ID().LineNo
	case 2:
		return p.Qty
	case 3:
		return p.DeletedAt()
	case 4:
		return p.CreatedAt()
	case 5:
		return p.UpdatedAt()
	}
	return nil
}

func softorderlineInsertColumns(p *SoftOrderLine) ([]string, []any) {
	return []string{"qty"}, []any{p.Qty}
}

func softorderlineScanReturning(p *SoftOrderLine, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	var k OrderLineKey
	if err := row.Scan(&k.OrderID, &k.LineNo, createdAtPtr, updatedAtPtr); err != nil {
		return err
	}
	p.SetID(k)
	return nil
}

// softorderlineNormalizeKey converts per-column driver values into a canonical OrderLineKey,
// so a key read back from the driver compares equal to PKValue.
func softorderlineNormalizeKey(v any) any {
	vals, ok := v.([]any)
	if !ok {
		return v
	}
	if len(vals) != 2 {
		return v
	}
	var k OrderLineKey
	f0, ok := drel.NormalizeIntKey(vals[0]).(int)
	if !ok {
		return v
	}
	k.OrderID = f0
	f1, ok := drel.NormalizeIntKey(vals[1]).(int)
	if !ok {
		return v
	}
	k.LineNo = LineNo(f1)
	return k
}

func softorderlineKeyIsZero(p *SoftOrderLine) bool {
	var zero OrderLineKey
	return p.ID() == zero
}

func softorderlineScanGenerated(p *SoftOrderLine, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(createdAtPtr, updatedAtPtr)
}

var SoftOrderLineMeta = drel.ModelMeta[SoftOrderLine]{
	Table:         "soft_order_lines",
	Columns:       []string{"order_id", "line_no", "qty", "deleted_at", "created_at", "updated_at"},
	PKColumns:     []string{"order_id", "line_no"},
	Scan:          scanSoftorderline,
	Snapshot:      snapshotSoftorderline,
	Diff:          diffSoftorderline,
	PKValue:       softorderlinePKValue,
	KeyValues:     softorderlineKeyValues,
	InsertColumns: softorderlineInsertColumns,
	ScanReturning: softorderlineScanReturning,
	ColumnValue:   softorderlineColumnValue,
	NormalizeKey:  softorderlineNormalizeKey,
	KeyStrategy:   drel.KeyAppAssigned,
	SetKey:        func(p *SoftOrderLine, key any) { p.SetID(key.(OrderLineKey)) },
	KeyIsZero:     softorderlineKeyIsZero,
	ScanGenerated: softorderlineScanGenerated,
	HasSoftDelete: true,
	Filters:       []drel.NamedFilter{drel.SoftDeleteFilter},
}

type SoftOrderLineRepository struct {
	*drel.Repository[SoftOrderLine]
}

func (r *SoftOrderLineRepository) FindByID(ctx context.Context, id OrderLineKey) (*SoftOrderLine, error) {
	return r.Find(ctx, id)
}

type TxSoftOrderLineRepository struct {
	*drel.TxRepository[SoftOrderLine]
}

func (r *TxSoftOrderLineRepository) FindByID(ctx context.Context, id OrderLineKey) (*SoftOrderLine, error) {
	return r.Find(ctx, id)
}
