// Code generated by drel. DO NOT EDIT.

package testmodels

import (
	"context"
	"time"

	"github.com/alternayte/drel"
)

var SoftVersionedOrderLines = struct {
	OrderID   drel.OrderedColumn[int]
	LineNo    drel.ComparableColumn[LineNo]
	Qty       drel.OrderedColumn[int]
	DeletedAt drel.ComparableColumn[*time.Time]
	Version   drel.OrderedColumn[int]
	CreatedAt drel.TimeColumn
	UpdatedAt drel.TimeColumn
}{
	OrderID:   drel.NewOrderedCol[int]("order_id"),
	LineNo:    drel.NewComparableCol[LineNo]("line_no"),
	Qty:       drel.NewOrderedCol[int]("qty"),
	DeletedAt: drel.NewComparableCol[*time.Time]("deleted_at"),
	Version:   drel.NewOrderedCol[int]("version"),
	CreatedAt: drel.NewTimeCol("created_at"),
	UpdatedAt: drel.NewTimeCol("updated_at"),
}

func scanSoftversionedorderline(row drel.Row) (*SoftVersionedOrderLine, error) {
	p := &SoftVersionedOrderLine{}
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	var k OrderLineKey
	err := row.Scan(&k.OrderID, &k.LineNo, &p.Qty, p.DeletedAtPtr(), p.VersionPtr(), createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	p.SetID(k)
	return p, nil
}

type softversionedorderlineSnapshot struct {
	Qty int
}

func snapshotSoftversionedorderline(p *SoftVersionedOrderLine) any {
	return softversionedorderlineSnapshot{Qty: p.Qty}
}

func diffSoftversionedorderline(p *SoftVersionedOrderLine, snap any) []drel.FieldChange {
	s := snap.(softversionedorderlineSnapshot)
	var changes []drel.FieldChange
	if p.Qty != s.Qty {
		changes = append(changes, drel.FieldChange{Column: "qty", Value: p.Qty})
	}
	return changes
}

func softversionedorderlinePKValue(p *SoftVersionedOrderLine) any {
	return p.ID()
}

// softversionedorderlineKeyValues splits a OrderLineKey into one value per key column, in key order.
func softversionedorderlineKeyValues(key any) []any {
	k := key.(OrderLineKey)
	return []any{k.OrderID, k.LineNo}
}

func softversionedorderlineColumnValue(p *SoftVersionedOrderLine, idx int) any {
	switch idx {
	case 0:
		return p.ID().OrderID
	case 1:
		return p.ID().LineNo
	case 2:
		return p.Qty
	case 3:
		return p.DeletedAt()
	case 4:
		return p.Version()
	case 5:
		return p.CreatedAt()
	case 6:
		return p.UpdatedAt()
	}
	return nil
}

func softversionedorderlineInsertColumns(p *SoftVersionedOrderLine) ([]string, []any) {
	return []string{"qty"}, []any{p.Qty}
}

func softversionedorderlineScanReturning(p *SoftVersionedOrderLine, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

// softversionedorderlineNormalizeKey converts per-column driver values into a canonical OrderLineKey,
// so a key read back from the driver compares equal to PKValue.
func softversionedorderlineNormalizeKey(v any) any {
	vals, ok := v.([]any)
	if !ok {
		return v
	}
	if len(vals) != 2 {
		return v
	}
	var k OrderLineKey
	f0, ok := drel.NormalizeIntKey(vals[0]).(int)
	if !ok {
		return v
	}
	k.OrderID = f0
	f1, ok := drel.NormalizeIntKey(vals[1]).(int)
	if !ok {
		return v
	}
	k.LineNo = LineNo(f1)
	return k
}

func softversionedorderlineKeyIsZero(p *SoftVersionedOrderLine) bool {
	var zero OrderLineKey
	return p.ID() == zero
}

func softversionedorderlineScanGenerated(p *SoftVersionedOrderLine, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(createdAtPtr, updatedAtPtr)
}

var SoftVersionedOrderLineMeta = drel.ModelMeta[SoftVersionedOrderLine]{
	Table:         "soft_versioned_order_lines",
	Columns:       []string{"order_id", "line_no", "qty", "deleted_at", "version", "created_at", "updated_at"},
	PKColumns:     []string{"order_id", "line_no"},
	Scan:          scanSoftversionedorderline,
	Snapshot:      snapshotSoftversionedorderline,
	Diff:          diffSoftversionedorderline,
	PKValue:       softversionedorderlinePKValue,
	KeyValues:     softversionedorderlineKeyValues,
	InsertColumns: softversionedorderlineInsertColumns,
	ScanReturning: softversionedorderlineScanReturning,
	ColumnValue:   softversionedorderlineColumnValue,
	NormalizeKey:  softversionedorderlineNormalizeKey,
	KeyStrategy:   drel.KeyAppAssigned,
	SetKey:        func(p *SoftVersionedOrderLine, key any) { p.SetID(key.(OrderLineKey)) },
	KeyIsZero:     softversionedorderlineKeyIsZero,
	ScanGenerated: softversionedorderlineScanGenerated,
	HasSoftDelete: true,
	Filters:       []drel.NamedFilter{drel.SoftDeleteFilter},
	HasVersioned:  true,
	VersionValue:  func(p *SoftVersionedOrderLine) int { return p.Version() },
	SetVersion:    func(p *SoftVersionedOrderLine, v int) { *p.VersionPtr() = v },
}

type SoftVersionedOrderLineRepository struct {
	*drel.Repository[SoftVersionedOrderLine]
}

func (r *SoftVersionedOrderLineRepository) FindByID(ctx context.Context, id OrderLineKey) (*SoftVersionedOrderLine, error) {
	return r.Find(ctx, id)
}

type TxSoftVersionedOrderLineRepository struct {
	*drel.TxRepository[SoftVersionedOrderLine]
}

func (r *TxSoftVersionedOrderLineRepository) FindByID(ctx context.Context, id OrderLineKey) (*SoftVersionedOrderLine, error) {
	return r.Find(ctx, id)
}
