// Code generated by drel. DO NOT EDIT.

package testmodels

import (
	"context"

	"github.com/alternayte/drel"
	uuid "github.com/google/uuid"
)

var TenantDocs = struct {
	TenantID  drel.ComparableColumn[uuid.UUID]
	DocNo     drel.OrderedColumn[int]
	Title     drel.StringColumn
	CreatedAt drel.TimeColumn
	UpdatedAt drel.TimeColumn
}{
	TenantID:  drel.NewComparableCol[uuid.UUID]("tenant_id"),
	DocNo:     drel.NewOrderedCol[int]("doc_no"),
	Title:     drel.NewStringCol("title"),
	CreatedAt: drel.NewTimeCol("created_at"),
	UpdatedAt: drel.NewTimeCol("updated_at"),
}

func scanTenantdoc(row drel.Row) (*TenantDoc, error) {
	p := &TenantDoc{}
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	var k TenantDocKey
	err := row.Scan(&k.TenantID, &k.DocNo, &p.Title, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	p.SetID(k)
	return p, nil
}

type tenantdocSnapshot struct {
	Title string
}

func snapshotTenantdoc(p *TenantDoc) any {
	return tenantdocSnapshot{Title: p.Title}
}

func diffTenantdoc(p *TenantDoc, snap any) []drel.FieldChange {
	s := snap.(tenantdocSnapshot)
	var changes []drel.FieldChange
	if p.Title != s.Title {
		changes = append(changes, drel.FieldChange{Column: "title", Value: p.Title})
	}
	return changes
}

func tenantdocPKValue(p *TenantDoc) any {
	return p.ID()
}

// tenantdocKeyValues splits a TenantDocKey into one value per key column, in key order.
func tenantdocKeyValues(key any) []any {
	k := key.(TenantDocKey)
	return []any{k.TenantID, k.DocNo}
}

func tenantdocColumnValue(p *TenantDoc, idx int) any {
	switch idx {
	case 0:
		return p.ID().TenantID
	case 1:
		return p.ID().DocNo
	case 2:
		return p.Title
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func tenantdocInsertColumns(p *TenantDoc) ([]string, []any) {
	return []string{"title"}, []any{p.Title}
}

func tenantdocScanReturning(p *TenantDoc, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

// tenantdocNormalizeKey converts per-column driver values into a canonical TenantDocKey,
// so a key read back from the driver compares equal to PKValue.
func tenantdocNormalizeKey(v any) any {
	vals, ok := v.([]any)
	if !ok {
		return v
	}
	if len(vals) != 2 {
		return v
	}
	var k TenantDocKey
	f0, ok := drel.NormalizeUUIDKey(vals[0]).(uuid.UUID)
	if !ok {
		return v
	}
	k.TenantID = f0
	f1, ok := drel.NormalizeIntKey(vals[1]).(int)
	if !ok {
		return v
	}
	k.DocNo = f1
	return k
}

func tenantdocKeyIsZero(p *TenantDoc) bool {
	var zero TenantDocKey
	return p.ID() == zero
}

func tenantdocScanGenerated(p *TenantDoc, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(createdAtPtr, updatedAtPtr)
}

var TenantDocMeta = drel.ModelMeta[TenantDoc]{
	Table:         "tenant_docs",
	Columns:       []string{"tenant_id", "doc_no", "title", "created_at", "updated_at"},
	PKColumns:     []string{"tenant_id", "doc_no"},
	Scan:          scanTenantdoc,
	Snapshot:      snapshotTenantdoc,
	Diff:          diffTenantdoc,
	PKValue:       tenantdocPKValue,
	KeyValues:     tenantdocKeyValues,
	InsertColumns: tenantdocInsertColumns,
	ScanReturning: tenantdocScanReturning,
	ColumnValue:   tenantdocColumnValue,
	NormalizeKey:  tenantdocNormalizeKey,
	KeyStrategy:   drel.KeyAppAssigned,
	SetKey:        func(p *TenantDoc, key any) { p.SetID(key.(TenantDocKey)) },
	KeyIsZero:     tenantdocKeyIsZero,
	ScanGenerated: tenantdocScanGenerated,
}

type TenantDocRepository struct {
	*drel.Repository[TenantDoc]
}

func (r *TenantDocRepository) FindByID(ctx context.Context, id TenantDocKey) (*TenantDoc, error) {
	return r.Find(ctx, id)
}

type TxTenantDocRepository struct {
	*drel.TxRepository[TenantDoc]
}

func (r *TxTenantDocRepository) FindByID(ctx context.Context, id TenantDocKey) (*TenantDoc, error) {
	return r.Find(ctx, id)
}
