// Code generated by drel. DO NOT EDIT.

package testmodels

import (
	"context"

	"github.com/alternayte/drel"
)

var VersionedOrderLines = struct {
	OrderID   drel.OrderedColumn[int]
	LineNo    drel.ComparableColumn[LineNo]
	Qty       drel.OrderedColumn[int]
	Version   drel.OrderedColumn[int]
	CreatedAt drel.TimeColumn
	UpdatedAt drel.TimeColumn
}{
	OrderID:   drel.NewOrderedCol[int]("order_id"),
	LineNo:    drel.NewComparableCol[LineNo]("line_no"),
	Qty:       drel.NewOrderedCol[int]("qty"),
	Version:   drel.NewOrderedCol[int]("version"),
	CreatedAt: drel.NewTimeCol("created_at"),
	UpdatedAt: drel.NewTimeCol("updated_at"),
}

func scanVersionedorderline(row drel.Row) (*VersionedOrderLine, error) {
	p := &VersionedOrderLine{}
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	var k OrderLineKey
	err := row.Scan(&k.OrderID, &k.LineNo, &p.Qty, p.VersionPtr(), createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	p.SetID(k)
	return p, nil
}

type versionedorderlineSnapshot struct {
	Qty int
}

func snapshotVersionedorderline(p *VersionedOrderLine) any {
	return versionedorderlineSnapshot{Qty: p.Qty}
}

func diffVersionedorderline(p *VersionedOrderLine, snap any) []drel.FieldChange {
	s := snap.(versionedorderlineSnapshot)
	var changes []drel.FieldChange
	if p.Qty != s.Qty {
		changes = append(changes, drel.FieldChange{Column: "qty", Value: p.Qty})
	}
	return changes
}

func versionedorderlinePKValue(p *VersionedOrderLine) any {
	return p.ID()
}

// versionedorderlineKeyValues splits a OrderLineKey into one value per key column, in key order.
func versionedorderlineKeyValues(key any) []any {
	k := key.(OrderLineKey)
	return []any{k.OrderID, k.LineNo}
}

func versionedorderlineColumnValue(p *VersionedOrderLine, idx int) any {
	switch idx {
	case 0:
		return p.ID().OrderID
	case 1:
		return p.ID().LineNo
	case 2:
		return p.Qty
	case 3:
		return p.Version()
	case 4:
		return p.CreatedAt()
	case 5:
		return p.UpdatedAt()
	}
	return nil
}

func versionedorderlineInsertColumns(p *VersionedOrderLine) ([]string, []any) {
	return []string{"qty"}, []any{p.Qty}
}

func versionedorderlineScanReturning(p *VersionedOrderLine, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	var k OrderLineKey
	if err := row.Scan(&k.OrderID, &k.LineNo, createdAtPtr, updatedAtPtr); err != nil {
		return err
	}
	p.SetID(k)
	return nil
}

// versionedorderlineNormalizeKey converts per-column driver values into a canonical OrderLineKey,
// so a key read back from the driver compares equal to PKValue.
func versionedorderlineNormalizeKey(v any) any {
	vals, ok := v.([]any)
	if !ok {
		return v
	}
	if len(vals) != 2 {
		return v
	}
	var k OrderLineKey
	f0, ok := drel.NormalizeIntKey(vals[0]).(int)
	if !ok {
		return v
	}
	k.OrderID = f0
	f1, ok := drel.NormalizeIntKey(vals[1]).(int)
	if !ok {
		return v
	}
	k.LineNo = LineNo(f1)
	return k
}

func versionedorderlineKeyIsZero(p *VersionedOrderLine) bool {
	var zero OrderLineKey
	return p.ID() == zero
}

func versionedorderlineScanGenerated(p *VersionedOrderLine, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(createdAtPtr, updatedAtPtr)
}

var VersionedOrderLineMeta = drel.ModelMeta[VersionedOrderLine]{
	Table:         "versioned_order_lines",
	Columns:       []string{"order_id", "line_no", "qty", "version", "created_at", "updated_at"},
	PKColumns:     []string{"order_id", "line_no"},
	Scan:          scanVersionedorderline,
	Snapshot:      snapshotVersionedorderline,
	Diff:          diffVersionedorderline,
	PKValue:       versionedorderlinePKValue,
	KeyValues:     versionedorderlineKeyValues,
	InsertColumns: versionedorderlineInsertColumns,
	ScanReturning: versionedorderlineScanReturning,
	ColumnValue:   versionedorderlineColumnValue,
	NormalizeKey:  versionedorderlineNormalizeKey,
	KeyStrategy:   drel.KeyAppAssigned,
	SetKey:        func(p *VersionedOrderLine, key any) { p.SetID(key.(OrderLineKey)) },
	KeyIsZero:     versionedorderlineKeyIsZero,
	ScanGenerated: versionedorderlineScanGenerated,
	HasVersioned:  true,
	VersionValue:  func(p *VersionedOrderLine) int { return p.Version() },
	SetVersion:    func(p *VersionedOrderLine, v int) { *p.VersionPtr() = v },
}

type VersionedOrderLineRepository struct {
	*drel.Repository[VersionedOrderLine]
}

func (r *VersionedOrderLineRepository) FindByID(ctx context.Context, id OrderLineKey) (*VersionedOrderLine, error) {
	return r.Find(ctx, id)
}

type TxVersionedOrderLineRepository struct {
	*drel.TxRepository[VersionedOrderLine]
}

func (r *TxVersionedOrderLineRepository) FindByID(ctx context.Context, id OrderLineKey) (*VersionedOrderLine, error) {
	return r.Find(ctx, id)
}
