// Code generated by drel. DO NOT EDIT.

package migrations

import "embed"

// FS holds the migrations of the "posts" module. Pass it to
// Engine.ApplyMigrationsFS together with the sets of the other modules.
//
//go:embed *.sql
var FS embed.FS
