package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// EmitMigrationsEmbed returns the source of the file that embeds one module's
// migrations. The host passes the FS of each module to
// Engine.ApplyMigrationsFS, which merges the sets in version order.
//
// pkgName is the Go package of the migration directory, and module is the name
// the file reports in its comment.
func EmitMigrationsEmbed(pkgName, module string) string {
	var b strings.Builder
	b.WriteString("// Code generated by drel. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	b.WriteString("import \"embed\"\n\n")
	b.WriteString(fmt.Sprintf("// FS holds the migrations of the %q module. Pass it to\n", module))
	b.WriteString("// Engine.ApplyMigrationsFS together with the sets of the other modules.\n")
	b.WriteString("//\n")
	b.WriteString("//go:embed *.sql\n")
	b.WriteString("var FS embed.FS\n")
	return b.String()
}

// migrationsPackageName derives the Go package name of a migration directory
// from its base name. A base name that cannot start a Go identifier falls back
// to "migrations", so the generated file always compiles.
func migrationsPackageName(dir string) string {
	base := filepath.Base(dir)
	if base == "" || !isASCIILetter(rune(base[0])) {
		return "migrations"
	}

	var b strings.Builder
	for _, r := range base {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r - 'A' + 'a')
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

func isASCIILetter(r rune) bool {
	return (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')
}

// WriteMigrationsEmbed writes the embed file into a module's migration
// directory. It writes nothing when the directory holds no .sql file, because
// a //go:embed pattern that matches nothing does not compile.
func WriteMigrationsEmbed(dir, module string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("codegen: read migration dir %s: %w", dir, err)
	}

	hasSQL := false
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".sql") {
			hasSQL = true
			break
		}
	}
	if !hasSQL {
		return false, nil
	}

	content, err := formatGenerated(EmitMigrationsEmbed(migrationsPackageName(dir), module))
	if err != nil {
		return false, fmt.Errorf("codegen: format the migration embed of %s: %w", dir, err)
	}
	if err := atomicWrite(filepath.Join(dir, "migrations_drel.go"), content); err != nil {
		return false, fmt.Errorf("codegen: write the migration embed of %s: %w", dir, err)
	}
	return true, nil
}
