package codegen

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestEmitMigrationsEmbed(t *testing.T) {
	out := EmitMigrationsEmbed("migrations", "posts")

	assert.Contains(t, out, "// Code generated by drel. DO NOT EDIT.")
	assert.Contains(t, out, "package migrations")
	assert.Contains(t, out, `import "embed"`)
	assert.Contains(t, out, "//go:embed *.sql")
	assert.Contains(t, out, "var FS embed.FS")
	assert.Contains(t, out, `"posts"`)
}

func TestMigrationsPackageName(t *testing.T) {
	assert.Equal(t, "migrations", migrationsPackageName("./internal/features/posts/migrations"))
	assert.Equal(t, "migrations", migrationsPackageName("db/migrations"))
	assert.Equal(t, "sql_files", migrationsPackageName("db/sql-files"))
	assert.Equal(t, "migrations", migrationsPackageName("/"))
	assert.Equal(t, "migrations", migrationsPackageName("/tmp/001"),
		"a base name that cannot start an identifier falls back")
}

func TestWriteMigrationsEmbed_SkipsAnEmptyDirectory(t *testing.T) {
	dir := t.TempDir()

	written, err := WriteMigrationsEmbed(dir, "posts")
	require.NoError(t, err)
	assert.False(t, written, "an embed of no files does not compile")

	_, err = os.Stat(filepath.Join(dir, "migrations_drel.go"))
	assert.True(t, os.IsNotExist(err))
}

func TestWriteMigrationsEmbed_MissingDirectoryIsNotAnError(t *testing.T) {
	written, err := WriteMigrationsEmbed(filepath.Join(t.TempDir(), "nope"), "posts")
	require.NoError(t, err)
	assert.False(t, written)
}

func TestWriteMigrationsEmbed_WritesWhenMigrationsExist(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "20260101000000_init.up.sql"),
		[]byte("CREATE TABLE posts (id INT);"), 0644))

	written, err := WriteMigrationsEmbed(dir, "posts")
	require.NoError(t, err)
	assert.True(t, written)

	content, err := os.ReadFile(filepath.Join(dir, "migrations_drel.go"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "//go:embed *.sql")
	assert.Contains(t, string(content), "package migrations",
		"a numeric temp directory falls back to the default package name")
}
