package codegen

import (
	"errors"
	"fmt"
	"go/format"
	"go/scanner"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

// generatedHeader marks files written by drel; only files starting with it are
// eligible for stale-file cleanup.
const generatedHeader = "// Code generated by drel. DO NOT EDIT."

// emitted holds the formatted content destined for a single output file.
type emitted struct {
	path    string
	content string
}

// ResolveModuleRoot finds the Go module root (the nearest ancestor directory
// containing go.mod) by walking up from startDir. It falls back to startDir when
// no go.mod is found, preserving the prior behaviour for configs that already sit
// at the module root.
func ResolveModuleRoot(startDir string) string {
	dir := startDir
	for {
		if fi, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil && !fi.IsDir() {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return startDir
		}
		dir = parent
	}
}

// Generate runs the full code generation pipeline atomically: it loads config,
// scans packages, validates the model set, emits and gofmts every output file
// in memory, and only then writes anything to disk (write-to-temp + rename). A
// failure at any step before the write phase leaves the working tree untouched.
//
// Stale generated *_drel.go files that would obstruct the package scan
// (because they reference deleted model types) are removed before scanning, but
// their contents are saved so they can be restored if any later step fails.
// After a successful write, truly stale files that no longer back any scanned
// model are permanently removed.
func Generate(configPath string) error {
	return GenerateModule(configPath, "")
}

// GenerateModule generates the code of one module of the config. An empty
// module name covers every module.
//
// The model files and the aggregated DB struct always cover every module,
// because the DB struct reaches all of the slices and a model file is the same
// whichever module asked for it. The module name selects which migration embeds
// are written.
func GenerateModule(configPath, module string) error {
	cfg, err := LoadConfig(configPath)
	if err != nil {
		return err
	}

	targets := cfg.ModuleList()
	if module != "" {
		one, err := cfg.Module(module)
		if err != nil {
			return err
		}
		targets = []ModuleConfig{one}
	}

	// Resolve the config file's directory as the working directory for scanning.
	cfgDir := filepath.Dir(configPath)
	if !filepath.IsAbs(cfgDir) {
		abs, err := filepath.Abs(cfgDir)
		if err != nil {
			return fmt.Errorf("codegen: resolve config dir: %w", err)
		}
		cfgDir = abs
	}

	// A config that declares an empty slice list describes an application with
	// no feature yet. Write the aggregated DB file so the db package compiles,
	// and scan nothing.
	if cfg.NoSlices {
		return writeDBFile(cfg, cfgDir, nil)
	}

	// Pre-scan stale removal: delete *_drel.go files from the package directories
	// so that stale generated code (referencing deleted types) does not cause
	// package-load errors in the subsequent ScanPackages call.
	// We save the contents first so they can be restored if any later step fails.
	saved, err := removeStaleInDirsWithBackup(cfg.AllPackages(), cfgDir)
	if err != nil {
		return err
	}

	// restoreOnFailure puts back any pre-scan-removed file if we return an error.
	// It is a no-op after a successful run (succeeded is set to true below).
	succeeded := false
	defer func() {
		if succeeded {
			return
		}
		for path, content := range saved {
			_ = atomicWrite(path, content)
		}
	}()

	// Patterns in drel.yaml (e.g. ./models) are resolved relative to the
	// directory that contains the config file. go/packages.Load discovers the
	// module root on its own from the working directory, so cfgDir is the
	// correct base -- NOT ResolveModuleRoot(cfgDir), which would resolve
	// ./models relative to the repo root when the config lives in a subdir.
	models, err := ScanPackages(cfg.AllPackages(), cfgDir)
	if err != nil {
		return err
	}

	if len(models) == 0 {
		return fmt.Errorf("codegen: no models found in packages %v", cfg.AllPackages())
	}

	// Tag each model with the feature slice that owns it, so the DB struct can
	// group the repositories. A config without modules leaves the tag empty.
	if len(cfg.Modules) > 0 {
		assignModules(models, cfg.ModuleList(), cfgDir)
	}

	// Give each enum type of a package to one model, so two models that share
	// an enum do not both declare its Values()/IsValid() helpers.
	assignEnumOwners(models)

	// Validate the whole model set before touching disk: duplicate DB field
	// names, unresolved relation targets, and column-less models all fail here
	// so a bad input never leaves a half-generated tree.
	if err := ValidateModels(models); err != nil {
		return err
	}

	// --- Emit + format everything into memory (no disk writes yet). ---
	var files []emitted
	intended := make(map[string]bool) // per-model output paths we will write

	for _, m := range models {
		content, err := EmitModelFileChecked(m)
		if err != nil {
			return err
		}
		formatted, err := formatGenerated(content)
		if err != nil {
			return fmt.Errorf("codegen: format model %q: %w", m.Name, err)
		}
		outPath := filepath.Join(m.Dir, strings.ToLower(m.Name)+"_drel.go")
		files = append(files, emitted{path: outPath, content: formatted})
		intended[outPath] = true
	}

	dbPath, dbContent, err := renderDBFile(cfg, cfgDir, models)
	if err != nil {
		return err
	}
	files = append(files, emitted{path: dbPath, content: dbContent})

	// --- Migration embeds: one for each target module that holds SQL files. ---
	for _, m := range targets {
		dir := m.Migrations
		if dir == "" {
			continue
		}
		if !filepath.IsAbs(dir) {
			dir = filepath.Join(cfgDir, dir)
		}
		if _, err := WriteMigrationsEmbed(dir, m.Name); err != nil {
			return err
		}
	}

	// --- Write phase: every file emitted and formatted successfully. ---
	// Signal success so the deferred restore does not put back stale files.
	succeeded = true
	for _, f := range files {
		if err := atomicWrite(f.path, f.content); err != nil {
			return fmt.Errorf("codegen: write %s: %w", f.path, err)
		}
	}

	// --- Remove stale generated *_drel.go files no longer backing a model. ---
	// Files removed before the scan that are now superseded by a freshly
	// written file (same path) are already gone; the rest stay gone because
	// the scan confirmed no model backs them.
	if err := removeStaleModelFiles(models, intended); err != nil {
		return err
	}

	return nil
}

// renderDBFile emits and formats the aggregated DB file, returning its absolute
// path and its content. It writes nothing.
func renderDBFile(cfg *Config, cfgDir string, models []ModelInfo) (string, string, error) {
	dbPath := cfg.Output.DB
	if !filepath.IsAbs(dbPath) {
		dbPath = filepath.Join(cfgDir, dbPath)
	}
	dbPkgName := filepath.Base(filepath.Dir(dbPath))
	content, err := formatGenerated(EmitDBFile(models, dbPkgName))
	if err != nil {
		return "", "", fmt.Errorf("codegen: format db file %s: %w", dbPath, err)
	}
	return dbPath, content, nil
}

// writeDBFile renders the aggregated DB file and writes it to disk.
func writeDBFile(cfg *Config, cfgDir string, models []ModelInfo) error {
	dbPath, content, err := renderDBFile(cfg, cfgDir, models)
	if err != nil {
		return err
	}
	if err := atomicWrite(dbPath, content); err != nil {
		return fmt.Errorf("codegen: write %s: %w", dbPath, err)
	}
	return nil
}

// formatGenerated gofmt-formats generated source. It performs no disk I/O; on a
// formatting error nothing is written by the caller and the error is returned.
//
// A formatting error means the emitter wrote invalid Go. gofmt reports only a
// line, a column and a parser message, which names neither the field nor the
// type at fault, so the offending source line is quoted into the error.
func formatGenerated(content string) (string, error) {
	formatted, err := format.Source([]byte(content))
	if err != nil {
		return "", withSourceLine(err, content)
	}
	return string(formatted), nil
}

// withSourceLine appends the emitted line that a parser error points at.
func withSourceLine(err error, content string) error {
	var list scanner.ErrorList
	if !errors.As(err, &list) || len(list) == 0 {
		return err
	}
	line := list[0].Pos.Line
	lines := strings.Split(content, "\n")
	if line < 1 || line > len(lines) {
		return err
	}
	return fmt.Errorf("%w\n\temitted line %d: %s", err, line, strings.TrimSpace(lines[line-1]))
}

// atomicWrite writes content to path via a temp file in the same directory
// followed by os.Rename, so a reader never sees a partially-written file.
func atomicWrite(path, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, ".drel-*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return err
	}
	if err := os.Chmod(tmpName, 0644); err != nil {
		os.Remove(tmpName)
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		os.Remove(tmpName)
		return err
	}
	return nil
}

// removeStaleInDirsWithBackup removes drel-generated *_drel.go files from the
// directories of the configured package patterns before scanning, and returns a
// map of path -> original content for every file that was removed. The caller
// can restore these files on failure to preserve atomicity.
func removeStaleInDirsWithBackup(patterns []string, dir string) (map[string]string, error) {
	saved := make(map[string]string)
	cfg := &packages.Config{
		Mode: packages.NeedFiles,
		Dir:  dir,
	}
	pkgs, err := packages.Load(cfg, patterns...)
	if err != nil {
		// If we can't load even file lists, proceed; the main scan will report the error.
		return saved, nil
	}
	for _, pkg := range pkgs {
		if len(pkg.GoFiles) == 0 {
			continue
		}
		pkgDir := filepath.Dir(pkg.GoFiles[0])
		entries, err := os.ReadDir(pkgDir)
		if err != nil {
			continue
		}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), "_drel.go") {
				continue
			}
			path := filepath.Join(pkgDir, e.Name())
			data, err := os.ReadFile(path)
			if err != nil {
				continue
			}
			if !strings.HasPrefix(string(data), generatedHeader) {
				continue // hand-written file
			}
			// Save content before removing so we can restore on failure.
			saved[path] = string(data)
			if err := os.Remove(path); err != nil {
				return saved, fmt.Errorf("codegen: remove stale %s: %w", path, err)
			}
		}
	}
	return saved, nil
}

// removeStaleModelFiles deletes drel-generated *_drel.go files in the scanned
// package directories that are not in the intended set (their backing model was
// deleted or renamed). Only files carrying the generated header are removed.
func removeStaleModelFiles(models []ModelInfo, intended map[string]bool) error {
	seenDirs := make(map[string]bool)
	for _, m := range models {
		if m.Dir == "" || seenDirs[m.Dir] {
			continue
		}
		seenDirs[m.Dir] = true

		entries, err := os.ReadDir(m.Dir)
		if err != nil {
			return fmt.Errorf("codegen: scan dir %s for stale files: %w", m.Dir, err)
		}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), "_drel.go") {
				continue
			}
			path := filepath.Join(m.Dir, e.Name())
			if intended[path] {
				continue
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return fmt.Errorf("codegen: read %s: %w", path, err)
			}
			if !strings.HasPrefix(string(data), generatedHeader) {
				continue // hand-written file that happens to match the suffix
			}
			if err := os.Remove(path); err != nil {
				return fmt.Errorf("codegen: remove stale %s: %w", path, err)
			}
		}
	}
	return nil
}
