// Code generated by drel. DO NOT EDIT.

package db

import (
	"context"

	"github.com/alternayte/drel"
	models "github.com/alternayte/drel/examples/relationships/models"
)

type DB struct {
	*drel.Engine
	Authors        *models.AuthorRepository
	AuthorProfiles *models.AuthorProfileRepository
	Books          *models.BookRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine:         engine,
		Authors:        &models.AuthorRepository{Repository: drel.NewRepository(engine, models.AuthorMeta)},
		AuthorProfiles: &models.AuthorProfileRepository{Repository: drel.NewRepository(engine, models.AuthorProfileMeta)},
		Books:          &models.BookRepository{Repository: drel.NewRepository(engine, models.BookMeta)},
	}, nil
}

// TxRepos holds the tracked repositories of one transaction. Load through
// the fields, stage with Add and Remove, then let WithTx commit.
type TxRepos struct {
	Authors        *models.TxAuthorRepository
	AuthorProfiles *models.TxAuthorProfileRepository
	Books          *models.TxBookRepository
}

// Tx returns the tracked repositories bound to the transaction in ctx.
// It panics if no transaction is present, so wrap the call in WithTx.
func (db *DB) Tx(ctx context.Context) TxRepos {
	tx := drel.MustFromContext(ctx)
	return TxRepos{
		Authors:        &models.TxAuthorRepository{TxRepository: drel.NewTxRepository(tx, models.AuthorMeta)},
		AuthorProfiles: &models.TxAuthorProfileRepository{TxRepository: drel.NewTxRepository(tx, models.AuthorProfileMeta)},
		Books:          &models.TxBookRepository{TxRepository: drel.NewTxRepository(tx, models.BookMeta)},
	}
}

// WithTx runs fn inside a transaction and puts that transaction in the
// context it passes to fn. Reach the tracked repositories with db.Tx(ctx).
// A nested call opens a savepoint on the same transaction.
func (db *DB) WithTx(ctx context.Context, fn func(ctx context.Context) error, opts ...drel.TxOption) error {
	return db.Engine.WithTx(ctx, fn, opts...)
}

var AuthorBooksRel = drel.RelationInfo{
	Name:        "Books",
	Type:        drel.HasMany,
	FKColumn:    "author_id",
	RelatedMeta: drel.ToMetaBase(&models.BookMeta),
	FieldSetter: func(parent any, related any) {
		p := parent.(*models.Author)
		items := related.([]any)
		result := make([]*models.Book, len(items))
		for i, item := range items {
			result[i] = item.(*models.Book)
		}
		p.Books = result
	},
}

var AuthorIncludeBooks = drel.NewIncludeSpec(&AuthorBooksRel)

var AuthorProfileRel = drel.RelationInfo{
	Name:        "Profile",
	Type:        drel.HasOne,
	FKColumn:    "author_id",
	RelatedMeta: drel.ToMetaBase(&models.AuthorProfileMeta),
	FieldSetter: func(parent any, related any) {
		p := parent.(*models.Author)
		p.Profile = related.(*models.AuthorProfile)
	},
}

var AuthorIncludeProfile = drel.NewIncludeSpec(&AuthorProfileRel)

var BookAuthorRel = drel.RelationInfo{
	Name:        "Author",
	Type:        drel.BelongsTo,
	FKColumn:    "author_id",
	RelatedMeta: drel.ToMetaBase(&models.AuthorMeta),
	FieldSetter: func(parent any, related any) {
		p := parent.(*models.Book)
		p.Author = related.(*models.Author)
	},
}

var BookIncludeAuthor = drel.NewIncludeSpec(&BookAuthorRel)
