// Code generated by drel. DO NOT EDIT.

package db

import (
	"context"

	"github.com/alternayte/drel"
	posts "github.com/alternayte/drel/examples/feature-slices/features/posts"
	users "github.com/alternayte/drel/examples/feature-slices/features/users"
)

type DB struct {
	*drel.Engine
	Posts   *posts.PostRepository
	Users   *users.UserRepository
	Modules Modules
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine: engine,
		Posts:  &posts.PostRepository{Repository: drel.NewRepository(engine, posts.PostMeta)},
		Users:  &users.UserRepository{Repository: drel.NewRepository(engine, users.UserMeta)},
		Modules: Modules{
			Posts: PostsRepos{
				Posts: &posts.PostRepository{Repository: drel.NewRepository(engine, posts.PostMeta)},
			},
			Users: UsersRepos{
				Users: &users.UserRepository{Repository: drel.NewRepository(engine, users.UserMeta)},
			},
		},
	}, nil
}

// TxRepos holds the tracked repositories of one transaction. Load through
// the fields, stage with Add and Remove, then let WithTx commit.
type TxRepos struct {
	Posts   *posts.TxPostRepository
	Users   *users.TxUserRepository
	Modules TxModules
}

// Tx returns the tracked repositories bound to the transaction in ctx.
// It panics if no transaction is present, so wrap the call in WithTx.
func (db *DB) Tx(ctx context.Context) TxRepos {
	tx := drel.MustFromContext(ctx)
	return TxRepos{
		Posts: &posts.TxPostRepository{TxRepository: drel.NewTxRepository(tx, posts.PostMeta)},
		Users: &users.TxUserRepository{TxRepository: drel.NewTxRepository(tx, users.UserMeta)},
		Modules: TxModules{
			Posts: PostsTxRepos{
				Posts: &posts.TxPostRepository{TxRepository: drel.NewTxRepository(tx, posts.PostMeta)},
			},
			Users: UsersTxRepos{
				Users: &users.TxUserRepository{TxRepository: drel.NewTxRepository(tx, users.UserMeta)},
			},
		},
	}
}

// PostsRepos holds the untracked repositories of the "posts" module.
type PostsRepos struct {
	Posts *posts.PostRepository
}

// PostsTxRepos holds the tracked repositories of the "posts" module.
type PostsTxRepos struct {
	Posts *posts.TxPostRepository
}

// UsersRepos holds the untracked repositories of the "users" module.
type UsersRepos struct {
	Users *users.UserRepository
}

// UsersTxRepos holds the tracked repositories of the "users" module.
type UsersTxRepos struct {
	Users *users.TxUserRepository
}

// Modules groups the untracked repositories by feature slice, so a slice
// reaches only its own models.
type Modules struct {
	Posts PostsRepos
	Users UsersRepos
}

// TxModules groups the tracked repositories by feature slice. Every set is
// bound to the same transaction.
type TxModules struct {
	Posts PostsTxRepos
	Users UsersTxRepos
}

// WithTx runs fn inside a transaction and puts that transaction in the
// context it passes to fn. Reach the tracked repositories with db.Tx(ctx).
// A nested call opens a savepoint on the same transaction.
func (db *DB) WithTx(ctx context.Context, fn func(ctx context.Context) error, opts ...drel.TxOption) error {
	return db.Engine.WithTx(ctx, fn, opts...)
}
