// Code generated by drel. DO NOT EDIT.

package db

import (
	"context"

	"github.com/alternayte/drel"
	models "github.com/alternayte/drel/examples/getting-started/models"
)

type DB struct {
	*drel.Engine
	Tasks *models.TaskRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine: engine,
		Tasks:  &models.TaskRepository{Repository: drel.NewRepository(engine, models.TaskMeta)},
	}, nil
}

// TxRepos holds the tracked repositories of one transaction. Load through
// the fields, stage with Add and Remove, then let WithTx commit.
type TxRepos struct {
	Tasks *models.TxTaskRepository
}

// Tx returns the tracked repositories bound to the transaction in ctx.
// It panics if no transaction is present, so wrap the call in WithTx.
func (db *DB) Tx(ctx context.Context) TxRepos {
	tx := drel.MustFromContext(ctx)
	return TxRepos{
		Tasks: &models.TxTaskRepository{TxRepository: drel.NewTxRepository(tx, models.TaskMeta)},
	}
}

// WithTx runs fn inside a transaction and puts that transaction in the
// context it passes to fn. Reach the tracked repositories with db.Tx(ctx).
// A nested call opens a savepoint on the same transaction.
func (db *DB) WithTx(ctx context.Context, fn func(ctx context.Context) error, opts ...drel.TxOption) error {
	return db.Engine.WithTx(ctx, fn, opts...)
}
