// Code generated by drel. DO NOT EDIT.

package db

import (
	"context"

	"github.com/alternayte/drel"
	articles "github.com/alternayte/drel/examples/model-features/articles"
)

type DB struct {
	*drel.Engine
	Articles *articles.ArticleRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine:   engine,
		Articles: &articles.ArticleRepository{Repository: drel.NewRepository(engine, articles.ArticleMeta)},
	}, nil
}

// TxRepos holds the tracked repositories of one transaction. Load through
// the fields, stage with Add and Remove, then let WithTx commit.
type TxRepos struct {
	Articles *articles.TxArticleRepository
}

// Tx returns the tracked repositories bound to the transaction in ctx.
// It panics if no transaction is present, so wrap the call in WithTx.
func (db *DB) Tx(ctx context.Context) TxRepos {
	tx := drel.MustFromContext(ctx)
	return TxRepos{
		Articles: &articles.TxArticleRepository{TxRepository: drel.NewTxRepository(tx, articles.ArticleMeta)},
	}
}

// WithTx runs fn inside a transaction and puts that transaction in the
// context it passes to fn. Reach the tracked repositories with db.Tx(ctx).
// A nested call opens a savepoint on the same transaction.
func (db *DB) WithTx(ctx context.Context, fn func(ctx context.Context) error, opts ...drel.TxOption) error {
	return db.Engine.WithTx(ctx, fn, opts...)
}
