// Code generated by drel. DO NOT EDIT.

package posts

import (
	"context"

	"github.com/alternayte/drel"
)

var Posts = struct {
	ID        drel.OrderedColumn[int]
	Title     drel.StringColumn
	AuthorID  drel.OrderedColumn[int]
	CreatedAt drel.TimeColumn
	UpdatedAt drel.TimeColumn
}{
	ID:        drel.NewOrderedCol[int]("id"),
	Title:     drel.NewStringCol("title"),
	AuthorID:  drel.NewOrderedCol[int]("author_id"),
	CreatedAt: drel.NewTimeCol("created_at"),
	UpdatedAt: drel.NewTimeCol("updated_at"),
}

func scanPost(row drel.Row) (*Post, error) {
	p := &Post{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Title, &p.AuthorID, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type postSnapshot struct {
	Title    string
	AuthorID int
}

func snapshotPost(p *Post) any {
	return postSnapshot{Title: p.Title, AuthorID: p.AuthorID}
}

func diffPost(p *Post, snap any) []drel.FieldChange {
	s := snap.(postSnapshot)
	var changes []drel.FieldChange
	if p.Title != s.Title {
		changes = append(changes, drel.FieldChange{Column: "title", Value: p.Title})
	}
	if p.AuthorID != s.AuthorID {
		changes = append(changes, drel.FieldChange{Column: "author_id", Value: p.AuthorID})
	}
	return changes
}

func postPKValue(p *Post) any {
	return p.ID()
}

func postColumnValue(p *Post, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Title
	case 2:
		return p.AuthorID
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func postInsertColumns(p *Post) ([]string, []any) {
	return []string{"title", "author_id"}, []any{p.Title, p.AuthorID}
}

func postScanReturning(p *Post, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

func postNormalizeKey(v any) any {
	return drel.NormalizeIntKey(v)
}

var PostMeta = drel.ModelMeta[Post]{
	Table:         "posts",
	Columns:       []string{"id", "title", "author_id", "created_at", "updated_at"},
	PKColumns:     []string{"id"},
	Scan:          scanPost,
	Snapshot:      snapshotPost,
	Diff:          diffPost,
	PKValue:       postPKValue,
	InsertColumns: postInsertColumns,
	ScanReturning: postScanReturning,
	ColumnValue:   postColumnValue,
	NormalizeKey:  postNormalizeKey,
}

type PostRepository struct {
	*drel.Repository[Post]
}

func (r *PostRepository) FindByID(ctx context.Context, id int) (*Post, error) {
	return r.Find(ctx, id)
}

type TxPostRepository struct {
	*drel.TxRepository[Post]
}

func (r *TxPostRepository) FindByID(ctx context.Context, id int) (*Post, error) {
	return r.Find(ctx, id)
}
