// Code generated by drel. DO NOT EDIT.

package users

import (
	"context"

	"github.com/alternayte/drel"
)

var Users = struct {
	ID        drel.OrderedColumn[int]
	Name      drel.StringColumn
	Email     drel.StringColumn
	CreatedAt drel.TimeColumn
	UpdatedAt drel.TimeColumn
}{
	ID:        drel.NewOrderedCol[int]("id"),
	Name:      drel.NewStringCol("name"),
	Email:     drel.NewStringCol("email"),
	CreatedAt: drel.NewTimeCol("created_at"),
	UpdatedAt: drel.NewTimeCol("updated_at"),
}

func scanUser(row drel.Row) (*User, error) {
	p := &User{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Name, &p.Email, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type userSnapshot struct {
	Name  string
	Email string
}

func snapshotUser(p *User) any {
	return userSnapshot{Name: p.Name, Email: p.Email}
}

func diffUser(p *User, snap any) []drel.FieldChange {
	s := snap.(userSnapshot)
	var changes []drel.FieldChange
	if p.Name != s.Name {
		changes = append(changes, drel.FieldChange{Column: "name", Value: p.Name})
	}
	if p.Email != s.Email {
		changes = append(changes, drel.FieldChange{Column: "email", Value: p.Email})
	}
	return changes
}

func userPKValue(p *User) any {
	return p.ID()
}

func userColumnValue(p *User, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Name
	case 2:
		return p.Email
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func userInsertColumns(p *User) ([]string, []any) {
	return []string{"name", "email"}, []any{p.Name, p.Email}
}

func userScanReturning(p *User, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

func userNormalizeKey(v any) any {
	return drel.NormalizeIntKey(v)
}

var UserMeta = drel.ModelMeta[User]{
	Table:         "users",
	Columns:       []string{"id", "name", "email", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanUser,
	Snapshot:      snapshotUser,
	Diff:          diffUser,
	PKValue:       userPKValue,
	InsertColumns: userInsertColumns,
	ScanReturning: userScanReturning,
	ColumnValue:   userColumnValue,
	NormalizeKey:  userNormalizeKey,
}

type UserRepository struct {
	*drel.Repository[User]
}

func (r *UserRepository) FindByID(ctx context.Context, id int) (*User, error) {
	return r.Find(ctx, id)
}

type TxUserRepository struct {
	*drel.TxRepository[User]
}

func (r *TxUserRepository) FindByID(ctx context.Context, id int) (*User, error) {
	return r.Find(ctx, id)
}
